org: yadav3033
app: lambda-demo
service: aws-python-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:CreateQueue
        - sqs:SendMessage
      Resource: '*'



functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
   

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: my-queue

