org: yadav3033
app: lambda-demo
service: aws-python-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:CreateQueue
        - sqs:SendMessage
      Resource: '*'


functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - schedule: cron(0/15 * * * ? *)


layers:
  pythonRequirements:
    name: PythonRequirementsLambdaLayer
    package:
      artifact: python.zip
    compatibleRuntimes:
      - python3.11

